# Transparência (0.0 totalmente transparente, 1.0 opaco)
background_opacity 0.85

# Desfoque do fundo (fica lindo no Hyprland)
background_blur 1

# Margem interna (pro texto não ficar colado na borda)
window_padding_width 15

# Cor das bordas da janela (no estilo Dracula)
active_border_color #bd93f9
inactive_border_color #44475a

# Desativa o borrão do sistema na janela (opcional, deixa mais nítido)
# Se quiser o efeito "frosed glass", controlamos isso pelo Hyprland
dynamic_background_opacity yes

# Fonte (Aproveitando que instalamos as Nerd Fonts)
font_family      Hack Nerd Font
font_size        11.0

# Remover a barra de título chata
window_padding_width 10

# Caminho para sua imagem
background_image /home/shdw/Wallpapers/ukiyoe1.jpg

# Como a imagem deve se comportar
background_image_layout scaled

# Opacidade da imagem (deixe bem baixo, tipo 0.05 a 0.1, para não atrapalhar a leitura do código)
background_image_linear no
background_tint 0.95
